11ty/eleventy

- cmd.js
- config.js
As discussed on Twitter, making a quick start with a minor update to top-level files. Let me know if any concerns. 👍
> Update to ES6 format

- README.md
> Fix read more links in README.md

- README.md
> Creating index.html: Avoid history expansion

- docs/permalinks.md
This adds documentation explaining how to generate files of different formats
> Document custom file formats in permalinks

- src/Engines/Liquid.js
- src/Engines/Nunjucks.js
- src/UserConfig.js
- test/TemplateConfigTest.js
- test/TemplateRenderLiquidTest.js
- test/TemplateRenderNunjucksTest.js
* Adds support for Nunjucks custom tags. Fixes #151
* Adds support for Shortcodes (supported in Nunjucks and LiquidJS). Fixes #13
> Shortcodes (and Nunjucks Custom Tags)

- src/EleventyServe.js
- src/Template.js
- src/UserConfig.js
- test/EleventyServeTest.js
> Pass in your own BrowserSync Configuration

- src/Engines/JavaScript.js
Potentially fixes #377. I’m not quite sure though, as the reporter’s environment is Windows and I get that error.
> Remove unused imports

- src/TemplatePath.js
> forces uses of posix path separator in url normalization

- src/UserConfig.js
I think this was a copy & paste error
> Fixing a typo

- README.md
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
Follow up of #555
> docs(README): add reference to plugins section of official docs.

- test/TemplateWriterTest.js
> Remove duplicate test keys

- .gitignore
Ignores folders created by source code editors like Visual Studio Code or IntelliJ WebStorm.
> Ignore idea settings folder

- test/EleventyErrorUtilTest.js
Increase test coverage to 100% for this file
> Test coverage for EleventyErrorUtil

- src/EleventyExtensionMap.js
- test/TemplateRenderJavaScriptTest.js
- test/TemplateWriterTest.js
> Add support for .11ty.cjs extensions

- src/Template.js
fix #786
Co-Authored-By: Dave Ceddia <dave@daveceddia.com>
> fix: don't throw an error on null date

- package.json
https://github.com/moment/luxon/blob/master/changelog.md#1220
> chore: minor bump luxon 1.22

- src/TemplateRender.js
Your comment (that made me smile by the way) said: 
> // todo use unshift or something (no wifi here to look up docs :D)
So here we go :).
PS. If you want to have the JS docs available offline, have a look at https://devdocs.io/offline.
> Replace concat by unshift as asked in comment

- LICENSE
- Update license year to 2020
- Add line break to the end of file
- Improves experience when using CLI tools
> docs: update license year to 2020

- src/Benchmark.js
- src/Eleventy.js
- src/EleventyWatch.js
- src/Engines/Html.js
- src/Engines/Liquid.js
- src/Engines/Markdown.js
- src/Engines/Nunjucks.js
- src/Engines/TemplateEngine.js
- src/Plugins/Pagination.js
- src/Template.js
- src/TemplateCollection.js
- src/TemplateContent.js
- src/TemplateData.js
- src/TemplateMap.js
- src/TemplateWriter.js
- src/Util/Sortable.js
Benchmark results:
https://gist.github.com/slightlyoff/4a2c2709c8a4ef80ef074010b0be6a65
API compatible; all tests pass.
> Initial, cleaned-up cut of performance tuning patches.

- src/Eleventy.js
- src/UserConfig.js
- src/Util/AsyncEventEmitter.js
- test/EleventyConfigTest.js
This is a pull request to enable async tasks in event handlers. (#1359)
Don't know if this was planned at all, but I thought it would be a cool feature.
The additional file changes were made automatically by the linter.
> add async EventEmitter

- src/Eleventy.js
- src/EleventyFiles.js
In a comment above the `getTemplateData` function, @zachleat said:
> // TODO make this a getter
So please find here my humble attempt to solve this TODO.
> Use getter/setter for getTemplateData

- src/EleventyServe.js
> Named broswer-sync instance

- src/Plugins/Pagination.js
PR is related to: #1555 and #1865
> Check `permalink` field before set extra output subdirectory for pagination

- src/Util/Sortable.js
- test/SortableTest.js
- test/TemplateCollectionTest.js
This PR contains some changes to the Sortable class, to make the API a little more consistent (IMO) while being backwards compatible.
> Add tests to get UT Coverage for utils/Sortable to 100

- test/MergeTest.js
See #2470 for more details why this is not (yet) 100.
> Add tests to get UT Coverage for utils/Merge to increase

- src/Eleventy.js
Normalization of added/changed file path(s) (via already existing `eleventy-utils`)
> Update Eleventy.js - incremental / Windows

- package.json
https://github.com/BrowserSync/browser-sync/pull/1995
Closes https://github.com/11ty/eleventy/issues/2680
**Havent tried this locally yet**
> Update browser-sync to resolve vulnerable qs version

- src/TemplateLayout.js
> Replaces reject with throw

- src/Plugins/I18nPlugin.js
Fixes https://github.com/11ty/eleventy/issues/2920
> Fix URL normalization when URL is current language

- README.md
Add Mastodon and Discord to Readme
> Add Mastodon and Discord to Readme

- src/Plugins/HtmlBasePlugin.js
- test/HtmlBasePluginTest.js
* src/Plugins/HtmlBasePlugin.js: Keep the hash if specified.
* test/HtmlBasePluginTest.js: Add tests.
> HtmlBasePlugin: Keep the URL hash
