11ty/eleventy

src/EleventyConfig.js, test/EleventyConfigTest.js
_(Implements #81)_
In this pull request:
- `EleventyConfig.addPassthroughCopy` returns a reference to `this` (the `EleventyConfig` object in this context)
- Tests for `EleventyConfig.addPassthroughCopy` are added
Should this be mentioned in [Pass-through File Copy: Manual Passthrough Copy (Faster)](https://github.com/11ty/eleventy/blob/master/docs/copy.md#manual-passthrough-copy-faster)? I could add a little example in the code snippet.
Also, you might not like the method documentation I added. However, I think it’s very helpful as some editors actually display this in a useful manner on hovering over function calls (e.g. VS Code).
=> Make EleventyConfig.addPassthroughCopy chainable

src/TemplatePassthrough.js, test/TemplatePassthroughTest.js
=> Ensures origin path isn’t included in output when targeting a directory

cmd.js, package.json, playground/pretty.html, src/Eleventy.js, src/Template.js, src/TemplatePath.js, test/TemplatePathTest.js
Switch to Browsersync for --serve (seamless reloads when watch finishes). Works transparently with `pathPrefix` to host your site in the subdirectory specified in your config file.
Smart reloads CSS files:
1. If they are in _includes, reload the entire page (css files included directly in <style>).
2. If they are anywhere else, injects them without reload.
Fixes #119
=> Use Browsersync for --serve

package.json
I recently found a bug in liquidjs (that required me to rewrite a template file that had worked with the liquid gem when I used Jekyll) and it was patched here: https://github.com/harttle/liquidjs/issues/72
I manually added the better liquidjs version to my local site & haven't found any regressions.
=> Update liquid to ^5.1.0

src/TemplatePath.js, test/EleventyFilesTest.js, test/stubs/glob-pages/about.md, test/stubs/glob-pages/contact.md, test/stubs/glob-pages/home.md
This adds a file exists check before statting the file.
This avoids an exception being thrown, but more importantly, allows glob
arguments to be passed as `--input`, fixing #173 in the process.
An example of a glob pattern that didn't work before, but will after this change, is:
```
$ eleventy --input=pages/!(contact.md)
```
It will process all file in the `pages` directory, except `contact.md`.
I've added a unit test for the glob argument, let me know if you'd like to see more checks!
=> Check whether file exists before isDirectory check

test/TemplateDataTest.js, test/TemplateTest.js
This pull requests:
- replaces all instances of `TemplateData()` in the tests with one of the following:
- `TemplateData("./")` when targetting the global (or project) directory
- `TemplateData("./test/")` when targetting a directory that doesn’t have a `_data` directory inside
- `TemplateData("./test/stubs/")` in all other cases
This fixes #362.
=> Fix: Tests invoking illegal constructor TemplateData() (fixes #362)

docs-src/.eleventy.docs.js, src/Eleventy.js, src/EleventyExtensionMap.js, src/EleventyFiles.js, src/EleventyWatchTargets.js, src/Engines/JavaScript.js, src/Engines/TemplateEngine.js, src/Template.js, src/TemplateData.js, src/TemplateFileSlug.js, src/TemplatePassthrough.js, src/TemplatePassthroughManager.js, src/TemplatePath.js, test/EleventyExtensionMapTest.js, test/TemplatePathTest.js, test/TemplateTest.js
Before tackling #368, I realized I needed to know more about `TemplatePath`’s utility functions. I went ahead and added documentation comments to every function. I also refactored some of them, mainly with the goal of simplifying the code.
I created a separate commit for each function because this makes it way easier to review the whole thing (e.g. function name changes are happening in the commit where that function is concerned). Should this get merged, you potentially want to squash all commits with the prefix `TemplatePath: ` into one. Your choice.
- `TemplatePath._getModuleDir`: <del>prefixed the function name with an underscore as it’s done in other files to signal that it’s only used in tests.</del><ins>See https://github.com/11ty/eleventy/pull/376#issuecomment-453755611</ins>
- …
=> Document & refactor the TemplatePath utilities

src/TemplatePath.js, test/TemplatePathTest.js
Reviewing https://github.com/11ty/eleventy/issues/484#issuecomment-482911190. See #484.
The `TemplatePath.getAllDirs` utility was broken by me in #376 and stopped handling paths with multiple segments with the same name correctly. A patched version in https://github.com/11ty/eleventy/commit/f5f5c618920982d52497775740d75cc02d84338c has the same bug, but differently. This pull request should fix variants of the bug.
=> Fix getAllDirs not handling segments of equal name

src/EleventyFiles.js, test/EleventyFilesTest.js
Fixes #509 
Note: I also added the `onlyFiles` flag since I BELIEVE we probably only want files, but someone can correct me if I'm wrong.
=> Make glob matching case insensitive

src/TemplateData.js
Fixes #556 where empty tags causes the merge to fail.
=> Check for empty tags

src/Eleventy.js, src/EleventyFiles.js
Closes #571 
While running `DEBUG=Eleventy* npx eleventy`, I noticed that the `Layouts` directory is not output along with the other config directories (`Input`, `Data`, `Includes`, `Output`). At first I thought I was configuring the `Layouts` directory incorrectly, and it took me a while to figure out that it simply wasn't in the debugging output.
This adds the `Layouts` directory to the debugging output. I thought it might save someone else the same trouble if they're trying to confirm that their `Layouts` directory is configured correctly.
=> Add Layouts Directory to debug output

src/TemplateConfig.js, test/TemplateConfigTest.js, test/stubs/config-promise.js
I attempted to use an async function in `.eleventy.js` because I wanted to try something depending on disk access, and usually do those things async. It turned out everything I tried to configure didn't work. The reason for this was that the config resolution doesn't handle async or promises, and just went ahead and merged my returned promise with the default config.
This PR makes the config resolution throw if a localConfig function returns a promise. Changing the entire flow to support async can be a major undertaking, but at least this addition will help future users identify their mistake clearly if they make the same one.
=> Throw when localConfig is a function that returns a promise

.travis.yml, src/Engines/JavaScript.js, test/TemplateRenderLiquidTest.js, test/TemplateRenderNunjucksTest.js, test/TemplateTest-JavaScript.js, test/stubs/class-norender.11ty.js, test/stubs/classfields-data.11ty.js, test/stubs/multipleexports-promises.11ty.js, test/stubs/multipleexports.11ty.js, test/stubs/object-norender.11ty.js, test/stubs/object.11ty.js, test/stubs/oneinstance.11ty.js
* When using class-based templates, use a single object instance for data and rendering.
* Add support for object-based JS templates a la `module.exports = { data: function() {}, render: function() {} }` and `module.exports.data = function() {}; module.exports.render = function() {};`
* Add support for Node v12+ feature: class fields a la:
```
module.exports = class {
data = {
title: 'hi',
};
render(data) {
return `
<p>${data.title}</p>
`;
}
};
```
* Fails gracefully when class or object definition is missing a render method (returns `""`), behaves similar to a data file.
Fixes #622.
=> Improve JavaScript templates

src/TemplateWriter.js
Adds missed `new` operators from commit 320af9bb0206d2befb0eafd4007481e3965a28ec
=> Fix broken error reporting when writing templates

src/Util/Merge.js, test/MergeTest.js
Among other things, this fixes #676 in which data that pertains to one file or directory can show up in completely unrelated files.
In debugging #676, I observed that `Template.getData()` during the async call to `this.addPageDate()` the contents of `mergedData` changes i.e. while we've yielded, another "thread" modifies the data. Essentially `mergedData` comes from various calls to `getData()`. With `dataDeepMerge` set to true, the data is merged rather than replaced.
Due to the logic in `Merge()` objects may end up with embedded shallow copies of objects that may later be modified by subsequent calls to `Merge()`. Here's the specific code in `getMergedItem`:
```
if (!target) {
return source;
} else if (Array.isArray(target) && Array.isArray(source)) {
...
} else {
// number, string, …
```
=> Merge logic flaw causes data spillage with dataDeepMerge = true

src/TemplateWriter.js
Fixes #722. Previously we wouldn't scope the value of the mapEntry variable to each iteration when looping over the templates to write. This became an issue of any of the generated promises threw an error, since the error message would always report that it stemmed from the template from the last iteration.
=> Scope mapEntry variable to for..of loop in TemplateWriter

package.json, src/TemplateData.js, src/UserConfig.js, test/TemplateDataTest.js, test/UserDataExtensionsTest.js, test/stubs-630/_data/globalData0.js, test/stubs-630/_data/globalData1.json, test/stubs-630/_data/globalData2.yaml, test/stubs-630/_data/globalData3.nosj, test/stubs-630/_data/subdir/globalDataSubdir.yaml, test/stubs-630/component-yaml/component.11tydata.js, test/stubs-630/component-yaml/component.11tydata.json, test/stubs-630/component-yaml/component.11tydata.nosj, test/stubs-630/component-yaml/component.11tydata.yaml, test/stubs-630/component-yaml/component.json, test/stubs-630/component-yaml/component.njk, test/stubs-630/component-yaml/component.yaml
See #635 for original comments. Fixes #630.
=> Gloryofrobots data hooks via #635

src/EleventyFiles.js
Checking for negative patterns in gitignore and eleventyignore files and and not processing them as files to ignore. This allows you to use the negative pattern (!filename) in your .gitignore and .eleventyignore files without eleventy skipping over everything and not processing your files.
=> Resolves #693 and #677

src/Util/Sortable.js, test/SortableTest.js
I decided to improve test coverage a bit in `Util/Sortable`, and found a couple issues.  Some of them were easy to fix, but others are above my pay-grade.
Pay special attention to the comments under `Alphabetic Ascending (shortcut)`
=> Improve Sortable test coverage; call out a bug; fix others

src/TemplateCollection.js, test/TemplateCollectionTest.js
Hello everyone,
in the light of #708 I decided to go with the custom collections for now while my amount of tags is still manageable. However, when creating my custom collections I discovered that there is no filter collections by multiple tags either and the `getFilteredByTag` method is not chainable. So I implemented a method that accepts either an array of values to filter by or a single value:
Single value:
Call is forwarded to the existing `getFilteredByTag` method and its result returned. Strictly speaking the method should return an error at this point and but hey this is JS and I'm a generous god ... err developer (_\*insert Xerxes meme\*_).
Array of values:
The method returns an array of elements which contain every value from the input array in its list of tags.
There are …
=> Add getFilteredByTags method and tests

src/TemplateData.js, test/UserDataExtensionsTest.js, test/stubs-630/_data/mergingGlobalData.js, test/stubs-630/_data/mergingGlobalData.json, test/stubs-630/_data/mergingGlobalData.nosj, test/stubs-630/_data/mergingGlobalData.yaml
This PR resolves #794 and also adds merging of global data from different files with the same base filename into one object
For example if we have files
```
//_data/data.js
module.exports = {
key1: "js-val1"
}
// _data/data.json
{
"key1": "json-val1",
"key2": "json-val2"
}
```
resulting data objects will be merged according to extension priority so ```js``` will override ```json```
```
{
"key1":  "js-val1",
"key2":  "json-val2"
}
```
Working on this PR I found that 11tydata.{json|js} files are not supported due to code in ```TemplateData.getObjectPathForDataFile```
I do not know if it is a bug or a normal behavior. To clarify this I created #820
=> Global data files priority according to file extensions  #794

package.json
https://github.com/okonet/lint-staged/releases
- Previously, lint-staged would allow empty commits in the situation where a linter task like "prettier --write" reverts all staged changes automatically. Now the default behaviour is to throw an error with a helpful warning message. The --allow empty option can be used to allow empty commits, or allowEmpty: true for the Node.js API.
- Node.js v8 is no longer supported because it will reach EOL on 2019-12-31
- Prior to version 10, tasks had to manually include git add as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects git add in task configurations, it will show a warning in the console. Please remove git add from …
=> chore: bump lint-staged to 10.0

src/Eleventy.js
The past participle of the verb "override" is "overridden", not "overrode".
We say: "foo overrode bar", but "bar was overriden by foo".
https://www.theconjugator.com/english/verb/to+override.html
=> Correct verb conjugation mistake in comment

src/Errors/TemplateContentPrematureUseError.js
In most files in the project, there is a line break between the const declarations on top and the class definition.
So I'm doing the same here to add some consistency.
The contrast is obvious when opening the 2 error files right after the other, as they should have the same layout but don't.
=> Make code style more coherent on error file

src/Engines/Ejs.js
I'm not sure what's the benefit of having a condition leading to an empty statement ?
You may have a good reason that I have missed though.
=> Inverse boolean logic to avoid empty statement

src/Engines/Haml.js
In pull request #969, you said:
> Ah yeah, this was an intentional leave—I want to keep it consistent!
So you decided to leave the unused `inputPath` param in the Handlebars engine in order to be consistent.
So following this logic, it would make sense to **add** this same unused `inputPath` param in the Haml engine's compile function, right?
As you can see from the search below, the Haml engine's compile function is the only one missing this input param:
Right?
=> Add inputPath to Haml eng. to improve consistency

test/EleventyFilesTest.js
In PR #967, I tried to refactor the `getTemplateData` function in `EleventyFiles.js`  by replacing the `if` and `return` by a ternary operator.
My refactor broke the caching but all the tests passed nonetheless.
On closing the PR, @zachleat said:
> Would be very interested in a PR that adds a test around this!
So here is the PR that adds a test around this.
What it does is simply call the `getTemplateData` function twice in a row and compares the return values.
Since the `getTemplateData` function returns an object, we can compare the object reference by using the `is` test.
I've been successfully able to break my test by removing the caching mechanism. In that case, the test result says:
> Values are deeply equal to each other, but they are not the same
Which is what we would expect …
=> Add getTemplateData caching test

src/Engines/JavaScript.js
Fixes `fn is not a function` error (#1012).
=> Throw error if nothing useful is returned from JS template

src/TemplatePassthroughManager.js
No big thang, just something I noticed when running in debug mode. It's useful to see this path properly.
=> Fix "[object Object]" in TemplatePassthrough debug message

src/Eleventy.js
While looking for a way to run code after a build has completed, either from watch or from a normal build, I came across `beforeWatch` code in the codebase. This extends that pattern to output `beforeBuild` and `afterBuild` events, too. Usecase for `afterBuild` is to trigger events only after Eleventy has run, for instance live reloading from a third-party server, or building a search index.
I'm also going to make a corresponding PR 11ty-website to document this functionality and `beforeWatch` (#1042)
=> Add `beforeBuild` and `afterBuild` events

.travis.yml, package.json
Currently, the minimum supported version is Node.js v8. Node.js v8 went EOL on December 31, 2019.
This PR updates both `engines` to check for at least Node.js 10 and the CI to only test on 10 and 12 (14 should be added at some point, since it'll be going LTS in ~October).
It seems that the docs may need to be updated, too.
I searched open PRs and couldn't find anything. Feel free to close this if it's unwelcome 🙇🏻‍♂️
=> chore: update minimum Node.js LTS version to v10 rather than the EOL v8

.github/workflows/ci.yml, .travis.yml
Node 15 is now released and [officially supported](https://nodejs.org/en/about/releases/) Node version.
=> Add Node 15 to CI

src/Template.js, test/TemplateTest.js
In `Template.js`, @zachleat asked of the `write` function:
> // TODO is this still used by anything but tests?
The answer is clearly no, so this function belongs to `TemplateTest.js` instead (the same way the local helper function `getRenderedData` does).
So I cut the function from `Template.js` where it was unused and pasted it to `TemplateTest.js`.
I had some adaptations to make regarding the input parameters and the value of `this`, as is often the case when porting a function from a file to another.
=> Move Template.write to TemplateTest, since only used there ("TODO" fix)

src/Plugins/Pagination.js, test/PaginationTest.js
Simply to have one less "TODO" in the code that could be fixed by a quick PR :).
The TODO said above the `getPagedItems` function:
> // TODO switch to a getter
=> Use getter for pagedItems in Pagination class ("TODO" fix)

src/Engines/Nunjucks.js, src/UserConfig.js, test/TemplateConfigTest.js
This PR allows registering Nunjucks globals through the eleventy config. The purpose of this is mainly to allow creating global template functions where filters and tags aren’t enough. 
A simple example:
in .eleventy.js
```js
eleventyConfig.addNunjucksGlobal("foobar", (str) => `foo ${str} bar`)
```
usage in a template file:
```nunjucks
{{ foobar("hello world") }}
```
Result:
```nunjucks
foo hello world bar
```
=> allow registering Nunjucks globals

src/Eleventy.js
This closes #833 and replaces #1066 as a solution. When I did some digging, I found out that the real problem here is that some errors are never caught by the `watchRun` callback. The `try` / `catch` is unused because the error is thrown inside of a `setTimeout`.
The fact that an exception is thrown means the build never gets marked as finished, causing `_watch` to do nothing:
https://github.com/11ty/eleventy/blob/8ffbb9927ea8482c5a46515f3a2ed25cd8830ad8/src/Eleventy.js#L441-L443
_But_ since the `try` / `catch` also doesn't work, Eleventy doesn't crash. Instead, it remains in this weird limbo state where the watcher continues to run but builds cease.
The fix has two parts:
1. Awaiting the `setTimeout` so that `try/catch` works
2. Making sure that we catch non-fatal errors and mark the …
=> Prevent unhandled errors from breaking watch mode

src/TemplateRender.js
List the supported engine extensions too as part of the error report, when you happen to feed 11ty an unsupported layout template file, e.g. `_data/layout/default.js` (note the lack of `.11ty` in that filename).
As also mentioned in #1081 this one had me thwarted for quite a while until I found out I had missed the **mandatory** `11ty` in `11ty.js` JavaScript Layout Template file naming -- it didn't help then that I hadn't found #1079 yet: once 11ty began to b0rk properly, this patch was the bit that would have sped me along the way a tad faster.
=> Improve user feedback when 11ty reports 'Unsupported engine'

src/EleventyFiles.js
This fixes Eleventy for configurations that output to the same directory as their input, or to a superdirectory of the input directory (ie. where the templates are kept in a subdirectory of the site).
=> Don't ignore output paths that contain all input (fixes #1129)

src/Eleventy.js, src/Engines/Nunjucks.js, src/EventBus.js, src/TemplateContent.js, test/TemplateTest.js
*TL;DR:* _this patch speeds up my local 11ty-work-only build steps by ~50%_
I noticed that running 11ty from upstream is much slower than the 0.11.x branch, which surprised me given some of the work I put in earlier this year. I don't have a root cause analysis, but it got annoying so I decided to see if I couldn't speed things up in my local workflow. This patch picks one of the low-hanging fruit I mused at back in May, caching intermediate template compiles after some profiling showed that repeated application of the same templates across many data files was causing NJK compilation to show up as heavy in my local blog project.
The benefits here are NJK specific (sorry, other template engines!) and probably brittle. Feedback on the patch appreciated.
```sh …
```
=> Cache intermediate NJK template compiles

src/Eleventy.js
```js
const Eleventy = require("@11ty/eleventy");
let elev = new Eleventy();
// bad: init was not called
elev
.write()
.catch(e => console.log(":("))
.then(r => console.log(":)"))
;
// good
elev.init().then(r => {
elev
.write()
.catch(e => console.log(":("))
.then(r => console.log(":)"))
;
}
```
before this was failing with
```
Problem writing Eleventy templates: (more in DEBUG output)
> Cannot read property 'write' of undefined
`TypeError` was thrown:
TypeError: Cannot read property 'write' of undefined
at Eleventy.executeBuild (@11ty/eleventy/src/Eleventy.js:835:31)
```
now it says
```
Problem writing Eleventy templates: (more in DEBUG output)
> Did you call Eleventy.init to create the TemplateWriter instance? Hint: you probably didn’t.
`Error` was thrown:
Error: Did you call …
```
=> elev.write: handle missing Eleventy.init

cmd.js, package.json, src/Eleventy.js, src/Engines/Nunjucks.js, src/Plugins/Pagination.js, src/Plugins/ServerlessBundlerPlugin.js, src/Plugins/ServerlessPlugin.js, src/Serverless.js, src/Template.js, src/TemplateBehavior.js, src/TemplateContent.js, src/TemplateMap.js, src/TemplatePermalink.js, src/UserConfig.js, test/TemplateMapTest.js, test/TemplatePermalinkTest.js, test/TemplateTest.js, test/stubs/eleventyExcludeFromCollectionsPermalinkFalse.njk, test/stubs/permalink-build-serverless-rendered/permalink-build-serverless-rendered.md, test/stubs/permalink-build-serverless/permalink-build-serverless.md, test/stubs/permalink-false-computed/test.md, test/stubs/permalink-nobuild/permalink-nobuild.md
Fixes https://github.com/11ty/eleventy/issues/1727
Fixes #1754 
Breaking change: `setBrowserSyncConfig` userland config method now deep merges by default
https://www.zachleat.com/web/eleventy-serverless-timeline/
=> Eleventy Serverless: Adds the Serverless utility and Serverless Bundler plugin

src/TemplateData.js, test/TemplateTest.js, test/stubs/data-cascade/template.11tydata.js
Resolves #1810.
As described in #1810, tags can be duplicated through a data deep merge if they appear in more than one place.
I can't think of a reason why anyone needs a tag to appear more than once within the data cascade, so this uses `new Set` to deduplicate the output.
Hopefully this is OK!
=> Deduplicate tags when using deepDataMerge

CODE_OF_CONDUCT.md
> I would love a follow up PR that adds a link to the top of the code of conduct in 11ty/eleventy to point to the website as the home base for the code of conduct, since technically now it lives in two places. - _[original comment by @zachleat ](https://github.com/11ty/11ty-website/pull/1109#issuecomment-883738110)_
This PR adds a link to the Code of Conduct (https://www.11ty.dev/docs/code-of-conduct/) which will exist when [#1109](https://github.com/11ty/11ty-website/pull/1109) in `11ty/11ty-website` lands.
I added some text "View the [Code of Conduct](foo) on 11ty.dev" but it could just be the `[Code of Conduct](link)`. Let me know and I'm happy to change it :)
=> Adds code of conduct link to top CODE_OF_CONDUCT.md

package.json, src/Engines/TemplateEngine.js, src/Template.js, src/TemplateConfig.js, src/TemplateContent.js, src/TemplateData.js, src/TemplateLayoutPathResolver.js
@zachleat proposed in #1891 removing fs-extra since the build in FS module now provides a promise based option and supports recursive options.
This Commit only uses the ```require("fs")``` instead of ```require("fs").promises``` or ```require("fs/promises")```, since the last one is not support in Node Version <14 and the sync API is used.
Except for Template.js no file logic needed to be changed to remove fs-extra.
According to my run of "npm test" test results are not changed by this commit.
This commit only replaces fs-extra with fs and does not touch existing logic when it's not needed. Maybe some optimizations like in 5ca1aa755dfb0fac76a86aba360c0cd7a78e780d are possible.
=> Remove fs-extra dependency (#1891)

src/EleventyBaseError.js
By extension, this will also document the signature for derived errors.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
I'm counting on your word, @zachleat :)
https://github.com/11ty/eleventy/issues/1885#issuecomment-880053251
=> docs: add docstring for EleventyBaseError

src/TemplateConfig.js
support `throw 'whatever';` in `.eleventy.js`
otherwise
```
TypeError: Cannot read property 'includes' of undefined
at TemplateConfig.mergeConfig (TemplateConfig.js)
```
in
```js
err.message.includes("Cannot find module")
```
=> TemplateConfig.js: make err.message optional

package.json, src/Template.js, src/TemplateData.js, src/TemplateFileSlug.js, src/TemplatePath.js, src/TemplatePermalink.js, test/TemplateWriterTest.js
As described in #1903 this commit removes the parse-filepath dependency from 11ty in favor of the native path.parse.
Some files needed renaming of some variables which were named "path" and shadowed the path module. I hope I selected reasonable replacements.
In TemplatePath.js I also changed the documentation links to point to the nodejs api doc instead of the npm package.
According to a local test run it does not change test results.
=> Remove parse-filepath dependency

src/Template.js
Demo: https://knokmki612.github.io/sandbox-11ty/
```sh
$ git clone https://github.com/knokmki612/sandbox-11ty.git
$ cd sandbox-11ty
$ yarn install
$ yarn eleventy
$ cat _site/parse-date-from-front-matter/index.html
<h1>Parse date from front matter</h1>
<p>date: Fri, 30 Apr 2021 00:00:00 GMT</p>
$ cat _site/2021-04-30/index.html
<h1>Parse date from filename</h1>
<p>date: Thu, 29 Apr 2021 15:00:00 GMT</p>
```
Doesn't match the results of date parsing between front-matter and filename.
This caused by unspecified the UTC timezone when parse date from filename.
According to [official document](https://www.11ty.dev/docs/dates/#dates-off-by-one-day), `page.date` must be the midnight of UTC
(in case of above example: `Fri, 30 Apr 2021 00:00:00 GMT`)
- My timezone: `Asia/Tokyo (GMT +09:00)`
=> Fix use local timezone unintentionally when parse date from filename

src/Util/AsyncEventEmitter.js
Introduced with https://github.com/11ty/eleventy/commit/554d7928308d52c128a88e716600cde8ff740d90
While I was at it, I made some small changes:
* looked after returning a homegeneous return value type
* `0` is falsy, so `!0` is true. I prefer to be more explicit by checking for the length against a number to get the Boolean
* An async function always returns a Promise, so there is no need for an additional `await`. See also https://jakearchibald.com/2017/await-vs-return-vs-return-await/ (last sentence). I can add the ESLint rule if you prefer. (That would be another PR since I can find 9 other instances of this pattern).
I'm happy to undo those changes if you prefer the old way.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> docs: document AsyncEventEmitter and harmonise function signature

src/Engines/Custom.js, src/TemplateEngineManager.js, test/TemplateRenderCustomTest.js
Resolves #1870 
☝️ Full description of this change over there!
=> Allow template engine overrides with addExtension, with access to the "default" engine

src/Engines/Nunjucks.js, test/TemplateRenderNunjucksTest.js
Nested async shortcodes would fail to correctly output content from the inner shortcode as eleventy wasn't waiting for the content to have processed before passing it to the parent.
The `body()` call takes a callback, which gets called when the passed content of a paired shortcode has finished rendering, both on async and sync templates.
Fixes #1053
=> Fix for nested nunjucks async shortcodes

src/Eleventy.js
The `eleventy --help` CLI output does not include the `--port` argument and description.
1. Run `node ./cmd.js --help`
2. Confirm the output includes the new `--port` argument and description
Closes #1938
=> [#1938]: Add --port argument and description to CLI --help output

src/Plugins/Pagination.js, test/PaginationTest.js, test/stubs/paged/paged-before-metadata.njk
This PR adds a second argument for passing page data in the paginations' `before` callback.
This is useful (especially when leveraging the Data Cascade, where a piece of metadata might be elsewhere in the cascade) when you want to process (filter or modify) based on a value in the frontmatter:
```js
---js
{
keyword: "item3",
pagination: {
data: "items",
size: 1,
before: function(data, metadata) {
return data.filter(el => el === metadata.keyword);
}
},
items: ["item1", "item2", "item3", "item4", "item5", "item6"]
}
---
{{ pagination.items[0] }} <- item3
```
=> Pagination: pass metadata to before callback

src/Engines/Liquid.js
- fixes undefined arguments in shortcodes and potentially other uses
- fixes #2348 and #2154
This fixes a major bug with liquid shortcodes not working in layout templates. They end up randomly getting `undefined` values for arguments after the first argument due to an order of execution issue with a changing `scope` context being sent to [evalValue](https://github.com/11ty/eleventy/compare/master...epelc:master#diff-cd8b0d5daef1e85d609f147e72a641e39dd0091c09dce6b8be1903e8dfd59a25R122).
I changed it from running the promise using await immediately to calling the promise immediately instead so it gets the correct current scope value. I then use `await Promise.all(pendingPromises)` to wait for each promise to resolve.
There is a separate example here which shows the differences in order of …
=> fix liquid template argument parsing and shortcode undefined values

test/TemplateTest.js, test/stubs/templateWithLiquidShortcodeMultipleArguments.liquid
I added a test for previous pr #2367 as per @zachleat.
It doesn't actually fail though on the old code as it only runs a single template file. I wasn't sure how to run multiple template files but this is everything else that's required. You need at least 2 pages to be rendered since this is an order of execution bug.
It does at least add a test for shortcodes which I think was missing anyways.
=> add test for pr #2367

src/ComputedDataTemplateString.js, src/EleventyErrorUtil.js, src/EleventyExtensionMap.js, src/TemplateContent.js, src/TemplateGlob.js, src/TemplateMap.js, src/TemplatePermalink.js, src/Util/Merge.js, test/EleventyErrorHandlerTest.js, test/TemplateRenderLiquidTest.js
String.prototype.substr() method is deprecated and no longer recommended. So replaced with String.prototype.slice() method.
=> chore: Replace deprecated String.prototype.substr() with String.prototype.slice()

src/TemplateFileSlug.js, test/TemplateFileSlugTest.js
Closes #1947 
`2021-11-20-my-awesome-post/index.md` gets a slug of `my-awesome-post` rather than `2021-11-20-my-awesome-post`.
=> Strip date from directory slugs

src/Plugins/Pagination.js
This is aiming to provide an update that resolves #731 and resolves #1185.
This patch adds the pagination option `renderEmpty`:
```yaml
pagination:
renderEmpty: true
```
This pull request probably needs a test written for it. I'm not sure what the process is like here.
Documentation is provided with 11ty/11ty-website#1327.
=> Support rendering empty data in pagination

src/TemplatePassthrough.js, src/TemplatePassthroughManager.js, src/UserConfig.js, test/TemplatePassthroughManagerTest.js, test/TemplateWriterTest.js, test/UserConfigTest.js
fix issue #530 
allow to pass options directly to [recursive-copy](https://www.npmjs.com/package/recursive-copy#arguments)
for example, to follow symlinks, set `{ expand: true }`
```js
eleventyConfig.addPassthroughCopy("node_modules/@fontsource/noto-sans", { expand: true });
eleventyConfig.addPassthroughCopy({
"node_modules/@fontsource/noto-sans": "css/noto-sans",
"node_modules/@fontsource/noto-mono": "css/noto-mono",
}, { expand: true });
```
todo: add docs to https://www.11ty.dev/docs/copy/
=> addPassthroughCopy: expose copyOptions, allow to follow symlinks

src/Template.js, src/Util/DateGitFirstAdded.js, test/EleventyTest.js, test/stubs-2224/index.njk
This change allows to use "git created" as a magic string to use the first appearance in git as the date of a template.
This uses gits feature to also track the file across renames.
If a file isn't yet tracked, it uses the current date.
It uses "git created" instead of "git first added", to keep closer to the already existing "created" option.
fixes #2224
=> #2224 git created option for date

src/defaultConfig.js
This change makes the `log` filter "passthrough" compatible, so you can put it in the middle of a filter chain.
That way you can use it like `{{ "Some Text" | log("Some logging") | upper }}`.
This fixes #2198.
=> Add passthrough logging filter #2198

src/EleventyFiles.js, src/UserConfig.js, test/EleventyFilesGitIgnoreEleventyIgnoreTest.js
It changes Eleventy default ignore from `node_modules/**` to `**/node_modules/**`.
https://github.com/11ty/eleventy/issues/2436
Docs section that will need to be updated => https://www.11ty.dev/docs/ignores/#node_modules
=> Ignore nested node modules by default

src/EleventyWatch.js, src/Util/PathNormalizer.js, src/Util/PathPrefixer.js, test/PathNormalizerTest.js
This change adds a "PathNormalizer" with tests which converts all paths to be unix compatible (replace "\" with "/"). That way auto reloading dependencies of the config also works on windows.
Sadly nested dependencies still always lag exactly one update behind, so if you have the following dependency graph:
- .eleventy.js depends on
- middle.js depends on
- nested.js
and you update nested, you see the following:
- do update 1 -> no result
- do update 2 -> see update 1
- do update 3 -> see update 2
During a short lookaround, I was unable to resolve this issue.
This should improve the situation around #1312
=> #1312 Improve situation for dependency monitoring

src/TemplateConfig.js
Fixes issue #2591 where `canary` builds are disregarding path prefixes set in .eleventy.js config file.
=> #2591 Fix for path prefix in canary build

src/EleventyShortcodeError.js, src/Engines/Nunjucks.js, src/Plugins/RenderPlugin.js
This fixes the following error, which obscures the actual issue causing an error to be thrown.
```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] EleventyShortcodeError is not defined (via ReferenceError)
[11ty] 
[11ty] Original error stack trace: ReferenceError: EleventyShortcodeError is not defined
[11ty]     at /path/to/project/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js:225:21
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
=> Import EleventyShortcodeError into RenderPlugin.js

src/TemplateContent.js
Unittests threw errors on windows because of some newline errors.
This happens with the most common git configs on windows.
This fix always checks for \n newlines in excerpts and that way fixes unittest execution on windows (which I use, so I mainly fixed it for myself)
=> Fix unittest execution on windows

package.json, src/index.d.ts
Hi 👋  - long time listener, first time caller!
I like to type my javascript files using JSDoc comments.  Thanks to an [excellent contribution](https://github.com/11ty/eleventy/pull/720) this is possible for the `.eleventy.js` config file 🎉 .  However, it can be more discoverable/easier with a small tweak 😄 ... that's where this here PR comes.
As discussed in #2033 the the way for 11ty consumers to get types is to reach into the 11ty package internals and find the type you want.  That's less than ideal for consumers and a bit fragile (if the file ever moves with a refactor or whatnot).
So this PR does 2 things:
1️⃣  - Makes an index.d.ts declaration file that can export types
2️⃣  - updates the package.json "types" property with the path to that type declaration file
So now a consuming …
=> feat: declare "types" in package.json to make consuming types easier

src/TemplateData.js
This change is to pass the currently processed file path to the custom data parser.
Reason to make this change is to be able to process the file along with it's dependencies that are imported with relative paths.
To do that parser needs to know what is the entry file path to be able to resolve relative imports.
Custom template parser provides file path already, but custom data parser provides only text content of the file.
=> feat: pass file path to custom data parser

src/TemplateRender.js
This change adresses the issue in #2386.
It changes the output for custom engines as follows:
Before:
```
[11ty] Writing _site/index2/index.html from ./index2.md (liquid)
[11ty] Writing _site/test/index.html from ./test.md (liquid)
[11ty] Writing _site/description/index.html from ./description.njk
[11ty] Writing _site/cloud/index.html from ./cloud.clowd
```
After:
```
[11ty] Writing _site/cloud/index.html from ./cloud.clowd (custom)
[11ty] Writing _site/description/index.html from ./description.njk
[11ty] Writing _site/index2/index.html from ./index2.md (custom/customName)
[11ty] Writing _site/test/index.html from ./test.md (custom/customName)
```
To configure the "customName", you can now add a key called `name` to the `addExtension` options object.
I set this PR to draft for now, to …
=> #2386 show custom engine label

src/Eleventy.js, src/EleventyServe.js, test/EleventyServeTest.js
This commit makes the EleventyServe module listen with the correct folder.
WARNING! This is still broken, as it doesn't update when you change the output directory!
Fixing this issue will likely involve a deeper look into which part of the "Server modules" are considered public/stable and how 11ty should interact with servers.
partly fixes #2311
=> #2311 First fix for cli output dir

src/Engines/Handlebars.js, src/Engines/JavaScript.js, src/Engines/Liquid.js, src/Engines/Nunjucks.js
Adds a more consistent `this` signature to Nunjucks and Liquid filters, as well as Handlebars helpers and JavaScript functions. Related to #1522.
The changes aim to make the this signature consistent for all filters added using `eleventyConfig.addFilter(...)` as well as the individual methods for the individual template languages. Example:
```javascript
eleventyConfig.addFilter("pagetitle", function(arg1, arg2) {
console.log("Called 'pagetitle' from " + this.page.inputPath);
return this.ctx.title;
})
```
The format of the this object is given by
```javascript
{
ctx: {
title: "...",
content: "...",  // (only in templates)
collections: [...],
...
},
page: {
inputPath: "...",
outputPath: "...",
url: "...",
...
}
}
```
It should still be discussed if this is a "good" format or if a better one …
=> Standardized `this` signature for filters

src/Plugins/ServerlessBundlerPlugin.js
An incorrectly named variable was added [here](https://github.com/11ty/eleventy/commit/786105e6f18feef27e0a2b8da4681725bce9a320#diff-99713a149e70b46dac489a0995bac49ab972cec22b54bc16f9b7ae704a9b62daR171). This fixes the issue
=> Fixes serverlessFilePath is not defined (2.0.0-beta.2) #2782

src/Engines/Markdown.js
This is a tiny improvement in ergonomics for replacing the underlying Markdown library. 
Due to some issues with `eleventyConfig.addExtension('md')`, namely that it opts you out of pre-processing (#2777) and that it causes issues with permalinks (#2780), `eleventyConfig.setLibrary('md')` remains the best way to replace the library.
At the moment, the library is tacitly assumed to be `markdown-it`, due to usage of library-specific methods (`set()`, `render()`, `disable()`), but there's no other reason why another library wouldn't work, as long as it provides a `render(str, data)` method. 
This PR makes the `set()` method optional in the replacement library.
=> Make Markdown library .set() method optional

src/Eleventy.js, src/Plugins/EdgePlugin.js, src/TemplateMap.js
This PR fixes three typos I spotted.
=> Fixing typos

package.json, src/Eleventy.js, src/EleventyExtensionMap.js, src/Engines/TemplateEngine.js, src/Template.js, src/TemplateCache.js, src/TemplateContent.js, src/TemplateData.js, src/TemplateEngineManager.js, src/TemplateLayout.js, src/TemplateLayoutPathResolver.js, src/TemplatePassthroughManager.js, src/TemplateRender.js, test/TemplateEngineManagerTest.js, test/TemplateLayoutPathResolverTest.js, test/TemplateLayoutTest.js, test/TemplateRenderJavaScriptTest.js, test/TemplateTest-JavaScript.js
Config instances were being cached in Eleventy Layout instances.
https://github.com/11ty/eleventy-plugin-bundle/issues/10
=> Saving/resetting config file should apply new config values everywhere (including layouts)

src/EleventyServe.js
All the other Eleventy modules have the `Eleventy:` prefix for their `debug()` namespace (including modules that have “Eleventy” in their name).
I think this was the only one doing it different.  It might make a difference for anyone filtering their debug messages with `Eleventy:*`.
=> fix: EleventyServe.js: update debug namespace

src/EleventyWatch.js
in `_watch()` in ..\@11ty\eleventy\src\Eleventy.js when calling `this.watchManager.getActiveQueue()` (line 802) an non empty array of path segments with `undefined` in the first and only array item might be returned.
This is unexpected and causes the error below.
`clearRequireCacheFor` is called with corrupted array.
`deleteRequireCache` is called with corrupted array.
`TemplatePath.absolutePath(...)` is used and breaks as it is not handling `undefined`;
This is happing when changing files and using autosave with --serve --incremental
flags and seems to be a racing condition problem that can be avoided by checking
`this.activeQueue.length` in `..\@11ty\eleventy\src\EleventyWatch.js`
} else if (this.incremental && this.activeQueue.length === 0) {
return [];
Stack Trace:
[11ty] Eleventy …
=> Problem with "Eleventy fatal watch error"

src/Eleventy.js
Pretty straightforward change to use inclusive language in the help text. Testable by running `npx eleventy --help` and scrolling down to the `--formats` flag's description.
Thanks for your consideration!
=> Use inclusive language in CLI help text

src/Engines/TemplateEngine.js, src/Plugins/EdgePlugin.js, src/Plugins/RenderPlugin.js, src/Template.js, src/TemplateData.js, src/TemplatePassthrough.js, test/TemplatePassthroughTest.js
This patch switches almost all usage of the `fs.*Sync` apis and `fs.promises.*` to using `graceful-fs` async promise versions instead. Required changing several methods and functions to be async but I believe they are all internal to the eleventy api(aka not a breaking change).
The only parts of eleventy which still use the sync apis after this are the initial config load ones.
There has been a history of EMFILE issues on windows with elventy. We've experience this in our own projects even on latest 2.0.1. These mostly stem from `addPassthroughCopy` but people have also had issues with a large number of template files. In our case we have a large number of image files(10k+).
https://github.com/11ty/eleventy/issues/2604
Although this patch does not fix it. Adding a graceful fs patch at the …
=> Refactor/switch to async fs operations after init/config load

package.json, src/index.d.ts
When we import values in a Typescript project, Typescript automatically infers the types using JSDoc comments if possible: https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#providing-type-hints-in-js-via-jsdoc. The present index.d.ts file is then just a redundancy on top of the Eleventy.js file, and requires additional maintenance to keep it up to date. 
This fixes #2935
=> #2935 Remove the .d.ts file and rely on JSDocs entirely

src/defaultConfig.js
I'm back after some hiatus to maybe sneak in a documentation or two before the v2.0 release :)
I was a bit confused where my doc command went (:eyes: #1885) but you can install `jsodc` and run
`node_modules/.bin/jsdoc -d ./api-docs -p ./package.json -R README.md src/` (resp. with `npx`) to generate files.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> Document default config using JSDoc docstrings

src/Plugins/Pagination.js, src/TemplateCollection.js, src/TemplateData.js, src/TemplateMap.js, test/TemplateCollectionTest.js, test/TemplateMapTest.js, test/TemplateWriterTest.js, test/stubs/collection/test10.md, test/stubs/collection/test8.md, test/stubs/collection/test9.md
This is a first implementation for #1175 and #2287 to gather feedback.
This change allows for more fine grained control over how a template is excluded from collections by allowing to set eleventyExcludeFromCollections to a tag or list of tags to exclude the template from.
This is meant as a first implementation for feedback. Also I'm not completely sure if excluding the `all` Collection is done correctly.
I only added minimal tests, but probably some more are needed.
=> #1175 and #2287 Allow eleventyExcludeFromCollections to take a list of tags

.editorconfig
As the author of this [Stack Overflow answer](https://stackoverflow.com/questions/35649847/objective-reasons-for-using-spaces-instead-of-tabs-for-indentation/75019495#75019495), I loved seeing the [recent commit which converted the codebase to tabs](https://github.com/11ty/eleventy/commit/358ec48f779fa34e14abef057cc1fa0c1a10aa45) :slightly_smiling_face: Well done :clap:
As explained in the SO answer, the indent size should only be a personal preference set in your code editor. So any dev can have their own preference.
The purpose of having tabs is to let the user chooses the indent size they prefer. Having `indent_size = 2` in the project's `.editorconfig` overrides the user's personal preference, which defeats this purpose.
=> Remove `indent_size` from `.editorconfig`

src/Eleventy.js
This closes [3230](https://github.com/11ty/eleventy/issues/3230). Changed the wording for the `--dryrun` help text to use the correct command for DEBUG mode. The new text also makes it a little more general in case someone has a different setup or expectations.
=> Fixes a small typo in the output of the `--help` command.

src/Engines/Liquid.js, test/TemplateRenderLiquidTest.js, test/stubs/_includes/custom-filter.liquid
This PR fixes https://github.com/11ty/eleventy/issues/3206.
The issue here is that in partials rendered using `{% render %}`, the `page` and `eleventy` variables do not exist, since the `{% render %}` tag is introducing a "new" scope that does not inherit the variables from the page it was called from. In `strictVariables` mode (this is an option you can pass to `.setLiquidOptions()`), this causes an error when you use any custom filter in such a partial, because Eleventy is trying to retrieve the value of the `page` and `eleventy` globals for use in the filter's definition.
This PR essentially turns the properties `page` and `eleventy` into getters; meaning that they are not retrieved until the user specifically uses them. This prevents filters that do not use these properties from …
=> Allow custom filters in Liquid partials in strictVariables mode

src/TemplatePassthrough.js
This is to ensure the same object is used for .before() and .after() calls, which makes this code work better with https://github.com/fqueze/11ty-fx-profiler/ that replaces the eleventyConfig.benchmarkManager implementation with another one that produces profiles the Firefox Profiler can understand.
=> Store the result of this.benchmarks.aggregate.get("Passthrough Copy File") in a variable

src/Plugins/InputPathToUrl.js, test/InputPathToUrlPluginTest.js, test/stubs-pathtourl/filter.njk, test/stubs-pathtourl/transform.njk
This PR should allow the [inputPathToUrl filter](https://www.11ty.dev/docs/filters/inputpath-to-url/) and the [input path to URL plugin](https://www.11ty.dev/docs/plugins/inputpath-to-url/) to handle hashes `#anchors`.  
Example, `my-blog-post.md#anchor` can become `/gh-pages/my-blog-post/#anchor`.
=> Allow inputPathToUrl to handle hashes (#anchor)

src/Template.js
I’m not sure how to implement a queue to resolve #3271 but here’s my proposed workaround. This does block everything while writing a template (hopefully a small window).
Closes #3271
Closes #2627
=> Write templates synchronously

package.json, src/Eleventy.js, src/index.d.ts
This basically reverts the changes from #3291 (and #2091), in favor of the approach from #3060. 
A new JSDoc `@typedef` comment ensures that `UserConfig` types are available (fixes #3097), *and* that everything exported from `Eleventy.js` has proper types (fixes #2935).
=> replace `index.d.ts` with jsdoc `@typedef`

src/EleventyFiles.js, src/Engines/JavaScript.js, src/Engines/Nunjucks.js, src/Filters/GetCollectionItem.js, src/GlobalDependencyMap.js, src/Plugins/Pagination.js, src/Plugins/RenderPlugin.js, src/Template.js, src/TemplateConfig.js, src/TemplateContent.js, src/TemplateMap.js, src/TemplatePassthroughManager.js, src/UserConfig.js
No change to behavior. A bit easier/faster to read. 😸
=> refactor: Use `?.` for terser conditionals

src/Eleventy.js
This is the counterpart to https://github.com/11ty/eleventy-dev-server/pull/85.
=> Makes stopWatch() async and graceful.

.github/workflows/ci.yml
Was waiting on https://github.com/actions/node-versions/pull/182 which shipped.
=> Restore Node 22.5 to GitHub Actions workflow

src/Util/HtmlTransformer.js
While plugins should be ordered, this attribute seems to be used as a map from an extension to that list of plugins rather than the list itself; as indicated in the `getPlugins()` method.
In my site I don't do any configuration of this, just using the defaults. While trying to update to Eleventy 3 I was running into errors
> Problem writing Eleventy templates:
> 1. Having trouble writing to "./public/css/base.css", "./public/css/base.css.map" from "./pages/styles.11ty.js" (via EleventyTemplateError)
> 2. Transform `@11ty/eleventy/html-transformer` encountered an error when transforming ./pages/styles.11ty.js. (via EleventyTransformError)
> 3. plugins is not iterable (via TypeError)
>
> Original error stack trace: TypeError: plugins is not iterable
>     at …
=> Fix type of HtmlTransformer plugins attribute

src/Template.js, src/TemplateContent.js, src/TemplateWriter.js
Move internal cache reset for incremental build files up to fix #3397
=> Fixes #3397

src/Template.js
The second argument in `.addPreprocessor()` seems to be designed to allow `"*"` to match all templating languages, but gets mapped to `".*"` before the actual comparison to `"*"` happens. As such, it is impossible to match all file types.
=> Fix wildcard in extensions argument in `.addPreprocessor()`

.gitignore, package-lock.json
Lockfiles exist to guarantee consistency across installs, especially in [CI tests](https://github.com/11ty/eleventy/blob/main/.github/workflows/ci.yml#L21)! This is a fresh lockfile from a fresh clone and install, and all tests are passing.
=> Commit lockfile for consistent CI and installs

src/Engines/Liquid.js
Fix #3425
This changes the import of liquidjs to proper import (same as in liquidjs's docs i mean)
It works with the latest version of liquidjs (10.16.5)
=> fix #3425 import of Liquid.js

src/TemplatePassthroughManager.js, test/TemplatePassthroughManagerTest.js
This fixes files with non-ASCII names not working (404) when server passthrough copy behavior is set to `"passthrough"` and the requested file is not already copied to the dist folder.
=> fix: encodeURI for passthrough aliases

src/Plugins/IdAttributePlugin.js, test/IdAttributePluginTest.js
Automatically resolve conflicts with other elements on the page that have an `id` attribute. Warning: preference given to first `id` found and any subsequent conflicting ids will be renamed.
```html
<div id="testing"></div>
<h1>Testing</h1>
```
becomes
```html
<div id="testing"></div>
<h1 id="testing-2">Testing</h1>
```
but
```html
<h1>Testing</h1>
<div id="testing"></div>
```
becomes
```html
<h1 id="testing">Testing</h1>
<div id="testing-2"></div>
```
Also adds a `filter` callback option to IdAttributePlugin per requested at #3424.
```js
eleventyConfig.addPlugin(IdAttributePlugin, {
filter: function({ page }) {
if(page.inputPath.endsWith("test-skipped.html")) {
return false;
}
return true;
}
});
```
=> Fixes #3424, conflicts with existing id attributes from IdAttributePlugin

src/Engines/Custom.js, src/Engines/JavaScript.js, src/Engines/TemplateEngine.js, src/TemplateContent.js, test/EleventyTest-Preprocessors.js, test/TemplateTest-CustomExtensions.js
* Adds `useJavaScriptImport` method to TemplateEngine class and enables by default for `JavaScript` (11ty.js) templates.
* `useJavaScriptImport` takes precedence over `needsToReadFileContents` (Custom template engine `read` property)
* Adds an `useJavaScriptImport` property to Custom template options (boolean)
https://www.11ty.dev/docs/languages/custom/#full-options-list
=> `addPreprocessor` support for `11ty.js` and Custom templates (via `useJavaScriptImport` property)

package-lock.json, package.json, src/Eleventy.js
This is a minimum viable patch that starts work on #3460. Notably, this change removes the requirement of `maxNodeModuleJsDepth` in `tsconfig.json` for TS packages that want to import UserConfig API, as mentioned [in the mega TS issue](https://github.com/11ty/eleventy/issues/3097#issuecomment-2423050317).
Since modifying the functionality of exports, imports, and declarations will involve some cleanup, removal and renaming, further work is probably something best left to the **next major** release.
I've removed the `@typedef` comment from `Eleventy.js`, since adding a `types` subpath export makes exporting it from Eleventy's main file redundant. If backwards compatiblity is needed, then something like this will implement the fuctionality offered by the subpath export:
```diff
/**
* …
```
=> Replace UserConfig typedef with a subpath export (#3460)

src/Util/Require.js
Fixes https://github.com/11ty/eleventy/issues/3518. Modules in Node 23 (possible 22, didn't test that) have both a `'module.exports'` key as well as a `'default'` key, and Eleventy doesn't know about the former. As such, it incorrectly identifies the module object as the exported object, which breaks things down the road. To resolve this, accept that the top-level object has a `'module.exports'` key that the object under the `'default'` key does not have.
=> Fix import-related error with CommonJS modules in Node 23

package.json, src/TemplateMap.js
For Eleventy sites with templates using shortcodes that do a lot of computation, rendering the template is the part of the build that takes the longest. This part is done sequentially.
This PR makes it happen in parallel, limiting the concurrency to the core count.
Example profiles, using the 11ty-website site as an example for benchmarking:
- when _site doesn't exist (causing eleventy-img to re-resize all images used by templates)
- with concurrency limited to 1 (matching current behavior) : https://share.firefox.dev/44vKeml (3.7s to render templates)
- with concurrency using all cores (10 on my laptop) : https://share.firefox.dev/4bjJnas (2.2s to render templates)
- when _site is already fully populated:
- with concurrency limited to 1 (matching current behavior) : …
=> Render templates in parallel.

src/Errors/EleventyErrorUtil.js
This PR may address the issue of https://github.com/11ty/eleventy/issues/2328, and resolves a downstream issue in https://github.com/noelforte/eleventy-plugin-vento/issues/120.
I've patched the static method `EleventyErrorUtil.isPrematureTemplateContentError` to search for instances of `TemplateContentPrematureUseError`s within `Error.cause` as well, so rethrown errors (from a Custom Template Language in my case) are properly caught by Eleventy.
As work on https://github.com/11ty/eleventy/issues/3582 continues, the implementation here could probably be cleaned up even more but I figured I'd start with this single patch.
I've also added additional changes in separate commits for the following:
1. Refactored the conditional to leverage optional chaining (`?.`)
2. Removed extra checks on …
=> Check `Error.cause` for `TemplateContentPrematureUseError` when rendering

src/EleventyServe.js
closes #3621 
cpuprof showed significant time spent loading libraries for the dev server. This ensures it is only imported when needed
```
~/Code/small/eleventyb: hyperfine "pnpm build" --warmup 1
Benchmark 1: pnpm build
Time (mean ± σ):     636.3 ms ±  88.6 ms    [User: 572.3 ms, System: 92.2 ms]
Range (min … max):   582.1 ms … 878.8 ms    10 runs
// after change
~/Code/small/eleventyb: hyperfine "pnpm build" --warmup 1
Benchmark 1: pnpm build
Time (mean ± σ):     593.4 ms ±  49.5 ms    [User: 551.8 ms, System: 88.3 ms]
Range (min … max):   533.4 ms … 701.4 ms    10 runs
```
tested by verifying `eleventy --serve` still works
assuming 50ms of savings, with 60k downloads per week, eleventy is likely called 100k times per week, or `5200000` times per year. This means this change will save …
=> perf: dynamic import dev server

src/Plugins/HtmlBasePlugin.js
Fixed issue where an error message referred to the wrong option name (`base` vs. `baseHref`), leading to confusion.
=> HtmlBasePlugin: Fix confusing error message

src/Eleventy.js, src/Engines/Html.js, src/LayoutCache.js, src/TemplateContent.js, src/TemplateLayout.js, src/TemplateMap.js, src/TemplateRender.js, test/LayoutCacheTest.js, test/stubs-3807/Issue3807test.js, test/stubs-3807/_layouts/base.html, test/stubs-3807/_layouts/home.html, test/stubs-3807/eleventy.config.js, test/stubs-3807/index.md
#3807 was caused by the HTML and Markdown engines are cacheable but Nunjucks is not, but did not use Nunjucks cacheable value when Nunjucks was the preprocessing engine.
This PR also includes some improves to make `Eleventy#watch()` more testable and renames the `TemplateCache` class to `LayoutCache` for more clarity on use.
=> Fix and test for #3807

src/Eleventy.js, src/TemplateConfig.js
Adds " - no configuration file" within the final output message to indicate that the run did not use a configuration file. This helps in cases where the user incorrectly thinks their configuration file is automatically picked up by Eleventy (such as e.g. `.eleventy.mjs`).
Fixes https://github.com/11ty/eleventy/issues/3654. For example, the error from a missing layout (as a result of a missing config file) would now be something along the lines of
```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Problem creating an Eleventy Layout for the "…" template file. (via EleventyBaseError)
[11ty] 2. You’re trying to use a layout that does not exist: _includes/… (via `layout: …`)
[11ty] 
[11ty] Original error stack trace: Error: …
[11ty]     at …
[11ty]     at …
[11ty] Wrote 0 files in 0.04 …
```
=> Add indicator for configuration-less runs
